licenses(["notice"])

package(default_visibility = ["//visibility:public"])

android_library(
        name = "vosk_models",
        manifest = "AndroidManifest.xml",
        assets = glob(["assets/*"]),
        assets_dir = "assets/",
        visibility = ["//visibility:public"],
        )
