package(default_visibility = ["//visibility:public"])

android_library(
        name = "wearableai_assets",
        manifest = "AndroidManifest.xml",
        assets = glob(["assets/**/*"]),
        assets_dir = "assets",
        visibility = ["//visibility:public"],
        )

